version: '3.8'
services:
  db:
    image: postgres:11.22-alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: feedback
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql

  app:
    image: 200605030904/mtabs-feedback:1.0.0
    container_name: app
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

volumes:
  db-data:
